spring.application.name=backend

# ----------------------------------------------------
# Supabase (PostgreSQL) Database Configuration
# ----------------------------------------------------
# 1. Supabase 접속 URL (Dashoard -> Project Settings -> Database -> Connection String (JDBC))
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres

# 2. Supabase 접속 계정 정보 (Username은 보통 postgres 계정 포맷, Password는 DB 생성 시 등록한 암호)
spring.datasource.username=postgres.bgjtnonkktumuslangiv
spring.datasource.password=HkWMWmeJI2krJaRx

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------------------
# JPA / Hibernate 설정
# ----------------------------------------------------
# 개발 서버에서는 DB 스키마 자동 생성 및 변경 (update)
spring.jpa.hibernate.ddl-auto=update

# 콘솔에 실행된 쿼리 표시 (포맷 지정)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
